name: Lint

on:
- pull_request_target

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Perform linting
        uses: stefanoeb/eslint-action@1.0.2
        with:
            files: src/
